version: "3.9"

services:
  auth-postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: auth-postgres
      POSTGRES_PASSWORD: auth-postgres
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-project-network

services:
  notes-postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: notes-postgres
      POSTGRES_PASSWORD: notes-postgres
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-project-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ai-project-network

  notes_service:
    container_name: note_service
    restart: always
    build: .  
    ports:
      - "8080:8000" 
    depends_on:
      - postgres
    networks:
      - ai-project-network
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres_db:5432/notes_db

volumes:
  postgres_data:

networks:
  ai-project-network:
    driver: bridge